export const STACK_AI_BACKEND_URL =
  process.env.NEXT_PUBLIC_STACK_AI_BACKEND_URL;
export const SUPABASE = {
  AUTH_URL: process.env.NEXT_PUBLIC_SUPABASE_AUTH_URL,
  ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  EMAIL_ADDRESS: process.env.NEXT_PUBLIC_SUPABASE_EMAIL,
  PASSWORD: process.env.NEXT_PUBLIC_SUPABASE_PASSWORD,
} as const;
